# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b8a4651f1aab11e42158aeb26c1ff60cd1212bdb34efadf01b9db39a3cc1fc2394d63aa2d2fd02a0f253a24f9b6e2f1d0533ead6c0550b9b44ec06c43ff16ac

test:
  secret_key_base: 29146b83bcdd02b19a77f94361e64a8454b77616d11f69fcd7911be8bc566919c15920244e079eb4adcd13256e59d41d3b430b9d48852c91def25a91044027d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
